// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptCallReducer from "../accept_call_reducer";
import DeclineCallReducer from "../decline_call_reducer";
import EndCallReducer from "../end_call_reducer";
import RequestCallReducer from "../request_call_reducer";
import SendAudioFrameReducer from "../send_audio_frame_reducer";
import SendMessageReducer from "../send_message_reducer";
import SendVideoFrameReducer from "../send_video_frame_reducer";
import SetNicknameReducer from "../set_nickname_reducer";

export type AcceptCallParams = __Infer<typeof AcceptCallReducer>;
export type DeclineCallParams = __Infer<typeof DeclineCallReducer>;
export type EndCallParams = __Infer<typeof EndCallReducer>;
export type RequestCallParams = __Infer<typeof RequestCallReducer>;
export type SendAudioFrameParams = __Infer<typeof SendAudioFrameReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SendVideoFrameParams = __Infer<typeof SendVideoFrameReducer>;
export type SetNicknameParams = __Infer<typeof SetNicknameReducer>;

