// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.uuid().name("session_id"),
  from: __t.identity(),
  to: __t.identity(),
  seq: __t.u32(),
  sampleRate: __t.u32().name("sample_rate"),
  channels: __t.u8(),
  rms: __t.f32(),
  pcm16Le: __t.byteArray().name("pcm_16_le"),
});
