// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ParticipantState,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.uuid().name("room_id"),
  identity: __t.identity(),
  get state() {
    return ParticipantState;
  },
  invitedBy: __t.identity().name("invited_by"),
  joinedAt: __t.option(__t.timestamp()).name("joined_at"),
  muted: __t.bool(),
  deafened: __t.bool(),
  camOff: __t.bool().name("cam_off"),
  serverMuted: __t.bool().name("server_muted"),
});
