// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  CallType,
} from "./types";


export default __t.row({
  roomId: __t.uuid().primaryKey().name("room_id"),
  get callType() {
    return CallType.name("call_type");
  },
  createdAt: __t.timestamp().name("created_at"),
  creator: __t.identity(),
});
