// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AudioFrameEvent = __t.object("AudioFrameEvent", {
  roomId: __t.uuid(),
  from: __t.identity(),
  seq: __t.u32(),
  sampleRate: __t.u32(),
  channels: __t.u8(),
  rms: __t.f32(),
  pcm16Le: __t.byteArray(),
});
export type AudioFrameEvent = __Infer<typeof AudioFrameEvent>;

export const CallParticipant = __t.object("CallParticipant", {
  id: __t.u64(),
  roomId: __t.uuid(),
  identity: __t.identity(),
  get state() {
    return ParticipantState;
  },
  invitedBy: __t.identity(),
  joinedAt: __t.option(__t.timestamp()),
});
export type CallParticipant = __Infer<typeof CallParticipant>;

export const CallRoom = __t.object("CallRoom", {
  roomId: __t.uuid(),
  get callType() {
    return CallType;
  },
  createdAt: __t.timestamp(),
  creator: __t.identity(),
});
export type CallRoom = __Infer<typeof CallRoom>;

// The tagged union or sum type for the algebraic type `CallType`.
export const CallType = __t.enum("CallType", {
  Voice: __t.unit(),
  Video: __t.unit(),
});
export type CallType = __Infer<typeof CallType>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  sentAt: __t.timestamp(),
  text: __t.string(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const MediaSettings = __t.object("MediaSettings", {
  id: __t.u32(),
  audioTargetSampleRate: __t.u32(),
  audioFrameMs: __t.u16(),
  audioMaxFrameBytes: __t.u32(),
  audioTalkingRmsThreshold: __t.f32(),
  videoWidth: __t.u16(),
  videoHeight: __t.u16(),
  videoFps: __t.u8(),
  videoJpegQuality: __t.f32(),
  videoMaxFrameBytes: __t.u32(),
  videoIframeInterval: __t.u8(),
});
export type MediaSettings = __Infer<typeof MediaSettings>;

// The tagged union or sum type for the algebraic type `ParticipantState`.
export const ParticipantState = __t.enum("ParticipantState", {
  Invited: __t.unit(),
  Joined: __t.unit(),
});
export type ParticipantState = __Infer<typeof ParticipantState>;

export const User = __t.object("User", {
  identity: __t.identity(),
  nickname: __t.string(),
  connectedAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const VideoFrameEvent = __t.object("VideoFrameEvent", {
  roomId: __t.uuid(),
  from: __t.identity(),
  seq: __t.u32(),
  width: __t.u16(),
  height: __t.u16(),
  isIframe: __t.bool(),
  jpeg: __t.byteArray(),
});
export type VideoFrameEvent = __Infer<typeof VideoFrameEvent>;

