// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AudioFrameEvent = __t.object("AudioFrameEvent", {
  sessionId: __t.uuid(),
  from: __t.identity(),
  to: __t.identity(),
  seq: __t.u32(),
  sampleRate: __t.u32(),
  channels: __t.u8(),
  rms: __t.f32(),
  pcm16Le: __t.byteArray(),
});
export type AudioFrameEvent = __Infer<typeof AudioFrameEvent>;

export const CallSession = __t.object("CallSession", {
  sessionId: __t.uuid(),
  get callType() {
    return CallType;
  },
  get state() {
    return CallState;
  },
  caller: __t.identity(),
  callee: __t.identity(),
  createdAt: __t.timestamp(),
  answeredAt: __t.option(__t.timestamp()),
});
export type CallSession = __Infer<typeof CallSession>;

// The tagged union or sum type for the algebraic type `CallState`.
export const CallState = __t.enum("CallState", {
  Ringing: __t.unit(),
  Active: __t.unit(),
});
export type CallState = __Infer<typeof CallState>;

// The tagged union or sum type for the algebraic type `CallType`.
export const CallType = __t.enum("CallType", {
  Voice: __t.unit(),
  Video: __t.unit(),
});
export type CallType = __Infer<typeof CallType>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  sentAt: __t.timestamp(),
  text: __t.string(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const MediaSettings = __t.object("MediaSettings", {
  id: __t.u32(),
  audioTargetSampleRate: __t.u32(),
  audioFrameMs: __t.u16(),
  audioMaxFrameBytes: __t.u32(),
  audioTalkingRmsThreshold: __t.f32(),
  videoWidth: __t.u16(),
  videoHeight: __t.u16(),
  videoFps: __t.u8(),
  videoJpegQuality: __t.f32(),
  videoMaxFrameBytes: __t.u32(),
});
export type MediaSettings = __Infer<typeof MediaSettings>;

export const User = __t.object("User", {
  identity: __t.identity(),
  nickname: __t.string(),
  connectedAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const VideoFrameEvent = __t.object("VideoFrameEvent", {
  sessionId: __t.uuid(),
  from: __t.identity(),
  to: __t.identity(),
  seq: __t.u32(),
  width: __t.u16(),
  height: __t.u16(),
  jpeg: __t.byteArray(),
});
export type VideoFrameEvent = __Infer<typeof VideoFrameEvent>;

