// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.uuid().name("session_id"),
  from: __t.identity(),
  to: __t.identity(),
  seq: __t.u32(),
  width: __t.u16(),
  height: __t.u16(),
  isIframe: __t.bool().name("is_iframe"),
  jpeg: __t.byteArray(),
});
