// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import DeclineInviteReducer from "../decline_invite_reducer";
import InviteToRoomReducer from "../invite_to_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import KickParticipantReducer from "../kick_participant_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import MuteAllReducer from "../mute_all_reducer";
import ResetMediaSettingsReducer from "../reset_media_settings_reducer";
import SendAudioFrameReducer from "../send_audio_frame_reducer";
import SendMessageReducer from "../send_message_reducer";
import SendVideoFrameReducer from "../send_video_frame_reducer";
import SetMediaStateReducer from "../set_media_state_reducer";
import SetNicknameReducer from "../set_nickname_reducer";
import SetParticipantServerMutedReducer from "../set_participant_server_muted_reducer";
import UnmuteAllReducer from "../unmute_all_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DeclineInviteParams = __Infer<typeof DeclineInviteReducer>;
export type InviteToRoomParams = __Infer<typeof InviteToRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type KickParticipantParams = __Infer<typeof KickParticipantReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type MuteAllParams = __Infer<typeof MuteAllReducer>;
export type ResetMediaSettingsParams = __Infer<typeof ResetMediaSettingsReducer>;
export type SendAudioFrameParams = __Infer<typeof SendAudioFrameReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SendVideoFrameParams = __Infer<typeof SendVideoFrameReducer>;
export type SetMediaStateParams = __Infer<typeof SetMediaStateReducer>;
export type SetNicknameParams = __Infer<typeof SetNicknameReducer>;
export type SetParticipantServerMutedParams = __Infer<typeof SetParticipantServerMutedReducer>;
export type UnmuteAllParams = __Infer<typeof UnmuteAllReducer>;

