// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  CallType,
  CallState,
} from "./types";


export default __t.row({
  sessionId: __t.uuid().primaryKey().name("session_id"),
  get callType() {
    return CallType.name("call_type");
  },
  get state() {
    return CallState;
  },
  caller: __t.identity(),
  callee: __t.identity(),
  createdAt: __t.timestamp().name("created_at"),
  answeredAt: __t.option(__t.timestamp()).name("answered_at"),
});
